openapi: 3.0.1
info:
  title: coding challenge
  description: Application service as coding challenge
  termsOfService: http://localhost:8080/tos
  contact:
    email: eric.phlippen@binaris-bibliothek.de
  version: 0.0.1
servers:
- url: http://localhost:8080/
paths:
  /createApplication:
    post:
      tags:
        - pet
      summary: Create a new application
      description: Create a new application
      operationId: createApplication
      requestBody:
        description: Create a new application
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'        
          
components:
  schemas:
    Application:
      required:
        - e-mail
        - name
        - githubUser
        - projects
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        e-mail:
          type: string
          example: eric.phlippen@binaris-informatik.de
        name:
          type: string
          example: Eric Phlippen
        githubUser:
          type: string
          example: fullsup1
        projects:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Projects'
    Projects:
      required:
        - name
        - employmentMode
        - capacity
        - duration
        - startingYear
        - role
        - teamSize
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        applicationId:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Inventory management
        employmentMode:
          type: string
          example: Freelance
        capacity:
          type: string
          example: full-time
        duration:
         type: string
         example: 3 Weeks
        startingYear:
          type: integer
          format: int64
          example: 2019
        role:
          type: string
          example: junior
        teamSize:
          type: integer
          format: int64
          example: 5
        repo:
          type: string
          example: https://github.com/fullsup1/coding-challenge-backend/tree/java
        liveUrl:
          type: string
          example: https://www.google.com/
